; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EasyCut"
#define MyAppVersion "4.0.0 2025.08.06"
#define MyAppPublisher "Easy Cut Nesting"
#define MyAppURL "http://www.easycutnesting.it"
#define MyAppExeName "setup.cmd"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{85669D80-5323-41BA-888A-72252BA5BD72}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest{516519B0-F79E-4C5A-9308-CE139F14D943}
OutputBaseFilename=EasyCutDownload 4.0.0 2025.08.06
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
;Source: "C:\EasyCut\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\EasyCutBeta\*"; DestDir: "{app}"; Excludes: "EasyCutBeta*.7z,EasyCutBeta*.zip,EasyCutBeta*.rar,Test,Note,ExampleCam,ExampleDstv,ExampleDxf,Source,Release,DOSLib 9.0,VbaModule,StorageApp,NewApp"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "C:\EasyCut\*"; DestDir: "{app}"; Excludes: "Test"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
;  ;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Parameters: /VERYSILENT; Flags: nowait


